server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: shopping-cart
              uri: http://shoppingcartms:8080
              predicates:
                - Path=/cart
                - Path=/cart/**
            - id: payment-service
              uri: http://paymentsms:8080
              predicates:
                - Path=/payments
                - Path=/payments/**
            - id: user-service
              uri: http://usersms:8080
              predicates:
                - Path=/users
                - Path=/users/**
