services:
  gateway:
    build: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - usersms
      - shoppingcartms
      - paymentsms

  shoppingcartms:
    build: ./shoppingcartms
    ports:
      - "8081:8080"

  paymentsms:
    build: ./paymentsms
    ports:
      - "8082:8080"
  usersms:
    build: ./usersms
    ports:
      - "8083:8080"
